#!/bin/bash
#
# The code is automatically generated by the Goland.
# Copyright © Aquarian-Age. All Rights Reserved.
# Licensed under MIT.
#
version="v0.0.0"
go build -ldflags="-s -w" -o ./luqin-$version .
GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o ./luqin-$version.exe .
